### ISSUE TITLE
You need to add `authy` credentials in `config/services.php`.

### ISSUE THREAD

**Issue by daniel-farina** [rinvex/laravel-authy#5]
Hi,

I'm going torugh the setup process and I always get the following , even though I have my key in the env file,  The application starts but fails to 

You need to add `authy` credentials in `config/services.php`.

**Comment by daniel-farina** [comment]
Ok the problem is that in the instructions it's missing the mode and the multiple keys that you can use. 

services.php

    'authy' => [
        'mode' => env('AUTHY_MODE'),
        'keys' => [
            'live' =>  env('AUTHY_KEY'),
            'production' =>  env('AUTHY_KEY_PRODUCTION'),
        ],

your .env should be

#Authy
AUTHY_KEY=KEY
AUTHY_KEY_PRODUCTION=KEY
AUTHY_MODE=live

**Comment by daniel-farina** [comment]
I found the correct configuration on the README after installing it composer. The master branch here is outdated. 

'authy' => [
    'mode' => env('AUTHY_MODE'),
    'keys' => [
        'production' => env('AUTHY_PRODUCTION_KEY'),
        'sandbox' => env('AUTHY_SANDBOX_KEY'),
    ],
],

**Comment by Omranic** [comment]
I'm closing this as it's no longer relevant with the latest versions, where the above mentioned environment variables were deprecated and removed, in favor to only one `AUTHY_SECRET` https://github.com/rinvex/laravel-authy#upgrade


>   API implementation is 100% backward compatible, but sandbox API has been dropped since it's officially deprecated. Also note that PHP7 is now required. Lastly the config options has been changed from `services.authy.mode`, `services.authy.keys.production`, and `services.authy.keys.sandbox` to only one key `services.authy.secret` for ease of use and consistency, accordingly the environment variables `AUTHY_MODE`, `AUTHY_PRODUCTION_KEY`, and `AUTHY_SANDBOX_KEY` are replaced with only one environment variable `AUTHY_SECRET`.
